url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/svgz.app" # the subpath of your site, e.g. /blog
title: "svgz.app" # the name of your site, e.g. ACME Corp.

defaults:
  -
    scope:
      path: "README.md"
    values:
      layout: "default"
      title: "README"