url: "https://svgz.app" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ""
title: "svgz.app"

defaults:
  -
    scope:
      path: "README.md"
    values:
      layout: "default"
      title: "README"